---
  - name: Install httpd in the server
    hosts: all
    become: true
    become_user: root

    tasks:
      - name: install the apache
        yum: 
          - name: httpd 
            state: present 
      - name: start the apache service
        service:
          - name: start the httpd 
            state: start


          
         

