apiVersion: app/v1
kind: Deployment
metadata:
     name: web-app
     labels:
        app: web-app
Spec:
  template:
     metadata:
       name: web-app
       labels:
          app: myapp
     spec:
       containers: 
          - name: httpd
            image: httpd
  replicas: 3
  selector:
     matchLabels:
        app: httpd 
        tier: web-app
        