apiVersion: app/v1
kind: Deployment
metadata:
     name: web-app
     labels:
        app: web-app
Spec:
  template:
     metadata:
       name: web-app
       labels:
          app: myapp
     spec:
       containers: 
          - name: tomcat
            image: tomcat:latest
  replicas: 3
  selector:
     matchLabels:
        app: httpd 
        tier: web-app
        

# kubectl create -f Deployment.yml
# kubectl get deployment
# kubectl get all